---
dependencies: []
galaxy_info:
  role_name: podman
  author: Calopsys
  company: Calopsys
  description: This role deploys a rootless podman base on a Debian system
  license: MIT
  min_ansible_version: 2.18.0
  issue_tracker_url: https://github.com/calopsys/ansible-collection-containers/issues
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - system
    - linux
    - containers
    - podman
    - rootless
