---
- name: Converge
  hosts: instance
  become: true
  tasks:
    - name: "Include docker role"
      ansible.builtin.import_role:
        name: calopsys.containers.docker

    # FIXME: can't find a way to make this work inside a podman container
    # - name: "Deploy foo.compose.yml"
    #   ansible.builtin.import_role:
    #     name: calopsys.containers.docker
    #     tasks_from: compose.yml
    #   vars:
    #     calopsys_docker_compose_workdir: "/opt/foo"
    #     calopsys_docker_compose_template: "foo.compose.yml"
    #
