---
- name: Converge
  hosts: instance
  become: true
  tasks:
    - name: "Include docker role"
      ansible.builtin.import_role:
        name: calopsys.containers.docker

    - name: "Deploy compose.yml"
      ansible.builtin.import_role:
        name: calopsys.containers.docker
        tasks_from: compose.yml
      vars:
        calopsys_docker_compose_workdir: "/opt/testapp"
        calopsys_docker_compose_template: "test.compose.yml.j2"
