---
- name: "Configure Docker daemon."
  ansible.builtin.template:
    src: "{{ calopsys_docker_config_daemon_template }}"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"
  when: calopsys_docker_config_daemon_template is defined and calopsys_docker_config_daemon_template | length > 0
  notify: "systemctl restart docker"
