---
- name: "Add docker repository."
  ansible.builtin.deb822_repository:
    name: "docker"
    enabled: true
    types: deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - "stable"
    architectures:
      - "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: "Install docker packages."
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
      - python3-docker
    update_cache: true
    install_recommends: false
